//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDownloader.TorrentShell.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDownloader.TorrentShell.Resources.Locales.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel_title {
            get {
                return ResourceManager.GetString("cancel_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File group.
        /// </summary>
        internal static string download_group_title {
            get {
                return ResourceManager.GetString("download_group_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start downloading.
        /// </summary>
        internal static string download_start_title {
            get {
                return ResourceManager.GetString("download_start_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string download_status_completed_title {
            get {
                return ResourceManager.GetString("download_status_completed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string download_status_connecting_title {
            get {
                return ResourceManager.GetString("download_status_connecting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string download_status_downloading_title {
            get {
                return ResourceManager.GetString("download_status_downloading_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string download_status_error_title {
            get {
                return ResourceManager.GetString("download_status_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string download_status_paused_title {
            get {
                return ResourceManager.GetString("download_status_paused_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string download_status_queued_title {
            get {
                return ResourceManager.GetString("download_status_queued_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying: {0}.
        /// </summary>
        internal static string download_status_retry_title {
            get {
                return ResourceManager.GetString("download_status_retry_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string open_folder_title {
            get {
                return ResourceManager.GetString("open_folder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string pause_title {
            get {
                return ResourceManager.GetString("pause_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this path for the “{0}” group.
        /// </summary>
        internal static string remember_group_path_title {
            get {
                return ResourceManager.GetString("remember_group_path_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string resume_title {
            get {
                return ResourceManager.GetString("resume_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string retry_title {
            get {
                return ResourceManager.GetString("retry_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to folder.
        /// </summary>
        internal static string save_to_title {
            get {
                return ResourceManager.GetString("save_to_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        internal static string select_folder_title {
            get {
                return ResourceManager.GetString("select_folder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File progress.
        /// </summary>
        internal static string torrent_files_progress_title {
            get {
                return ResourceManager.GetString("torrent_files_progress_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files in this torrent.
        /// </summary>
        internal static string torrent_files_title {
            get {
                return ResourceManager.GetString("torrent_files_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select torrent files.
        /// </summary>
        internal static string torrent_selector_app_title {
            get {
                return ResourceManager.GetString("torrent_selector_app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string torrent_selector_clear {
            get {
                return ResourceManager.GetString("torrent_selector_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string torrent_selector_continue {
            get {
                return ResourceManager.GetString("torrent_selector_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent.
        /// </summary>
        internal static string torrent_selector_default_name {
            get {
                return ResourceManager.GetString("torrent_selector_default_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the torrent files and destination. They will be downloaded together in this window..
        /// </summary>
        internal static string torrent_selector_description {
            get {
                return ResourceManager.GetString("torrent_selector_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The torrent selection session token is missing or invalid..
        /// </summary>
        internal static string torrent_selector_invalid_token_error {
            get {
                return ResourceManager.GetString("torrent_selector_invalid_token_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDownloader Core could not provide torrent metadata. {0}.
        /// </summary>
        internal static string torrent_selector_metadata_error {
            get {
                return ResourceManager.GetString("torrent_selector_metadata_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string torrent_selector_select_all {
            get {
                return ResourceManager.GetString("torrent_selector_select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} files · {2}.
        /// </summary>
        internal static string torrent_selector_selection_summary {
            get {
                return ResourceManager.GetString("torrent_selector_selection_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send the selection to PDownloader Core..
        /// </summary>
        internal static string torrent_selector_send_selection_error {
            get {
                return ResourceManager.GetString("torrent_selector_send_selection_error", resourceCulture);
            }
        }
    }
}
