//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDownloader.TorrentShell.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDownloader.TorrentShell.Resources.Locales.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All other file types.
        /// </summary>
        internal static string download_group_all_other_types {
            get {
                return ResourceManager.GetString("download_group_all_other_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files from torrent downloads.
        /// </summary>
        internal static string download_group_all_torrent_files {
            get {
                return ResourceManager.GetString("download_group_all_torrent_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File group.
        /// </summary>
        internal static string download_group_title {
            get {
                return ResourceManager.GetString("download_group_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string download_status_cancelled_title {
            get {
                return ResourceManager.GetString("download_status_cancelled_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string download_status_completed_title {
            get {
                return ResourceManager.GetString("download_status_completed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string download_status_connecting_title {
            get {
                return ResourceManager.GetString("download_status_connecting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string download_status_downloading_title {
            get {
                return ResourceManager.GetString("download_status_downloading_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string download_status_error_title {
            get {
                return ResourceManager.GetString("download_status_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging.
        /// </summary>
        internal static string download_status_merging_title {
            get {
                return ResourceManager.GetString("download_status_merging_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string download_status_paused_title {
            get {
                return ResourceManager.GetString("download_status_paused_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        internal static string download_status_queued_title {
            get {
                return ResourceManager.GetString("download_status_queued_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying: {0}.
        /// </summary>
        internal static string download_status_retrying_title {
            get {
                return ResourceManager.GetString("download_status_retrying_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this path for the “{0}” group.
        /// </summary>
        internal static string remember_group_path_title {
            get {
                return ResourceManager.GetString("remember_group_path_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to.
        /// </summary>
        internal static string save_to_title {
            get {
                return ResourceManager.GetString("save_to_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        internal static string select_folder_title {
            get {
                return ResourceManager.GetString("select_folder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDownloader TorrentShell.
        /// </summary>
        internal static string torrent_shell_app_title {
            get {
                return ResourceManager.GetString("torrent_shell_app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string torrent_shell_cancel {
            get {
                return ResourceManager.GetString("torrent_shell_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string torrent_shell_clear {
            get {
                return ResourceManager.GetString("torrent_shell_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string torrent_shell_close {
            get {
                return ResourceManager.GetString("torrent_shell_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected files are complete..
        /// </summary>
        internal static string torrent_shell_completed {
            get {
                return ResourceManager.GetString("torrent_shell_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent.
        /// </summary>
        internal static string torrent_shell_default_name {
            get {
                return ResourceManager.GetString("torrent_shell_default_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose torrent files, then monitor and control every download here..
        /// </summary>
        internal static string torrent_shell_description {
            get {
                return ResourceManager.GetString("torrent_shell_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TorrentShell session token is missing or invalid..
        /// </summary>
        internal static string torrent_shell_invalid_token_error {
            get {
                return ResourceManager.GetString("torrent_shell_invalid_token_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading torrent metadata….
        /// </summary>
        internal static string torrent_shell_loading_metadata {
            get {
                return ResourceManager.GetString("torrent_shell_loading_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDownloader Core could not provide torrent metadata. {0}.
        /// </summary>
        internal static string torrent_shell_metadata_error {
            get {
                return ResourceManager.GetString("torrent_shell_metadata_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string torrent_shell_open_folder {
            get {
                return ResourceManager.GetString("torrent_shell_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string torrent_shell_pause {
            get {
                return ResourceManager.GetString("torrent_shell_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} files completed.
        /// </summary>
        internal static string torrent_shell_progress_summary {
            get {
                return ResourceManager.GetString("torrent_shell_progress_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string torrent_shell_resume {
            get {
                return ResourceManager.GetString("torrent_shell_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string torrent_shell_retry {
            get {
                return ResourceManager.GetString("torrent_shell_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string torrent_shell_select_all {
            get {
                return ResourceManager.GetString("torrent_shell_select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one torrent file..
        /// </summary>
        internal static string torrent_shell_select_one_error {
            get {
                return ResourceManager.GetString("torrent_shell_select_one_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} files · {2}.
        /// </summary>
        internal static string torrent_shell_selection_summary {
            get {
                return ResourceManager.GetString("torrent_shell_selection_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start downloads.
        /// </summary>
        internal static string torrent_shell_start {
            get {
                return ResourceManager.GetString("torrent_shell_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the torrent downloads..
        /// </summary>
        internal static string torrent_shell_start_error {
            get {
                return ResourceManager.GetString("torrent_shell_start_error", resourceCulture);
            }
        }
    }
}
