//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDownloader.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDownloader.Resources.Locales.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about_app_title.
        /// </summary>
        internal static string about_app_title {
            get {
                return ResourceManager.GetString("about_app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about_us_title.
        /// </summary>
        internal static string about_us_title {
            get {
                return ResourceManager.GetString("about_us_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_author_created_summary.
        /// </summary>
        internal static string app_author_created_summary {
            get {
                return ResourceManager.GetString("app_author_created_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_capitalized_name_title.
        /// </summary>
        internal static string app_capitalized_name_title {
            get {
                return ResourceManager.GetString("app_capitalized_name_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_description_summary.
        /// </summary>
        internal static string app_description_summary {
            get {
                return ResourceManager.GetString("app_description_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_name_title.
        /// </summary>
        internal static string app_name_title {
            get {
                return ResourceManager.GetString("app_name_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_short_name_title.
        /// </summary>
        internal static string app_short_name_title {
            get {
                return ResourceManager.GetString("app_short_name_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_slogan_summary.
        /// </summary>
        internal static string app_slogan_summary {
            get {
                return ResourceManager.GetString("app_slogan_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_sort_slogan_summary.
        /// </summary>
        internal static string app_sort_slogan_summary {
            get {
                return ResourceManager.GetString("app_sort_slogan_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clean_title.
        /// </summary>
        internal static string clean_title {
            get {
                return ResourceManager.GetString("clean_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close_title.
        /// </summary>
        internal static string close_title {
            get {
                return ResourceManager.GetString("close_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact_us_title.
        /// </summary>
        internal static string contact_us_title {
            get {
                return ResourceManager.GetString("contact_us_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dep_lib_title.
        /// </summary>
        internal static string dep_lib_title {
            get {
                return ResourceManager.GetString("dep_lib_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_add_link_title.
        /// </summary>
        internal static string dialog_add_link_title {
            get {
                return ResourceManager.GetString("dialog_add_link_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_button_abort_title.
        /// </summary>
        internal static string dialog_button_abort_title {
            get {
                return ResourceManager.GetString("dialog_button_abort_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_button_cancel_title.
        /// </summary>
        internal static string dialog_button_cancel_title {
            get {
                return ResourceManager.GetString("dialog_button_cancel_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_button_continue_title.
        /// </summary>
        internal static string dialog_button_continue_title {
            get {
                return ResourceManager.GetString("dialog_button_continue_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_button_Ignore_title.
        /// </summary>
        internal static string dialog_button_Ignore_title {
            get {
                return ResourceManager.GetString("dialog_button_Ignore_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_button_no_title.
        /// </summary>
        internal static string dialog_button_no_title {
            get {
                return ResourceManager.GetString("dialog_button_no_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_button_ok_title.
        /// </summary>
        internal static string dialog_button_ok_title {
            get {
                return ResourceManager.GetString("dialog_button_ok_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_button_retry_title.
        /// </summary>
        internal static string dialog_button_retry_title {
            get {
                return ResourceManager.GetString("dialog_button_retry_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_button_try_title.
        /// </summary>
        internal static string dialog_button_try_title {
            get {
                return ResourceManager.GetString("dialog_button_try_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_button_yes_title.
        /// </summary>
        internal static string dialog_button_yes_title {
            get {
                return ResourceManager.GetString("dialog_button_yes_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_link_title.
        /// </summary>
        internal static string dialog_link_title {
            get {
                return ResourceManager.GetString("dialog_link_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_warn_title.
        /// </summary>
        internal static string dialog_warn_title {
            get {
                return ResourceManager.GetString("dialog_warn_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_filter_searchbox_desc.
        /// </summary>
        internal static string download_filter_searchbox_desc {
            get {
                return ResourceManager.GetString("download_filter_searchbox_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_cancelled_title.
        /// </summary>
        internal static string download_status_cancelled_title {
            get {
                return ResourceManager.GetString("download_status_cancelled_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_completed_title.
        /// </summary>
        internal static string download_status_completed_title {
            get {
                return ResourceManager.GetString("download_status_completed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_connecting_title.
        /// </summary>
        internal static string download_status_connecting_title {
            get {
                return ResourceManager.GetString("download_status_connecting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_downloading_title.
        /// </summary>
        internal static string download_status_downloading_title {
            get {
                return ResourceManager.GetString("download_status_downloading_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_error_title.
        /// </summary>
        internal static string download_status_error_title {
            get {
                return ResourceManager.GetString("download_status_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_merging_title.
        /// </summary>
        internal static string download_status_merging_title {
            get {
                return ResourceManager.GetString("download_status_merging_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_paused_title.
        /// </summary>
        internal static string download_status_paused_title {
            get {
                return ResourceManager.GetString("download_status_paused_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_queued_title.
        /// </summary>
        internal static string download_status_queued_title {
            get {
                return ResourceManager.GetString("download_status_queued_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_retrying_title.
        /// </summary>
        internal static string download_status_retrying_title {
            get {
                return ResourceManager.GetString("download_status_retrying_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_file_cap_loaded_title.
        /// </summary>
        internal static string download_view_file_cap_loaded_title {
            get {
                return ResourceManager.GetString("download_view_file_cap_loaded_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_file_end_time_title.
        /// </summary>
        internal static string download_view_file_end_time_title {
            get {
                return ResourceManager.GetString("download_view_file_end_time_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_file_name_title.
        /// </summary>
        internal static string download_view_file_name_title {
            get {
                return ResourceManager.GetString("download_view_file_name_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_file_save_path_title.
        /// </summary>
        internal static string download_view_file_save_path_title {
            get {
                return ResourceManager.GetString("download_view_file_save_path_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_file_start_time_title.
        /// </summary>
        internal static string download_view_file_start_time_title {
            get {
                return ResourceManager.GetString("download_view_file_start_time_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_file_status_title.
        /// </summary>
        internal static string download_view_file_status_title {
            get {
                return ResourceManager.GetString("download_view_file_status_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_file_url_title.
        /// </summary>
        internal static string download_view_file_url_title {
            get {
                return ResourceManager.GetString("download_view_file_url_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_sort_filename_az_title.
        /// </summary>
        internal static string download_view_sort_filename_az_title {
            get {
                return ResourceManager.GetString("download_view_sort_filename_az_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_sort_filename_za_title.
        /// </summary>
        internal static string download_view_sort_filename_za_title {
            get {
                return ResourceManager.GetString("download_view_sort_filename_za_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_sort_filesize_asc_title.
        /// </summary>
        internal static string download_view_sort_filesize_asc_title {
            get {
                return ResourceManager.GetString("download_view_sort_filesize_asc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_sort_filesize_desc_title.
        /// </summary>
        internal static string download_view_sort_filesize_desc_title {
            get {
                return ResourceManager.GetString("download_view_sort_filesize_desc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_sort_filetime_end_asc_title.
        /// </summary>
        internal static string download_view_sort_filetime_end_asc_title {
            get {
                return ResourceManager.GetString("download_view_sort_filetime_end_asc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_sort_filetime_end_desc_title.
        /// </summary>
        internal static string download_view_sort_filetime_end_desc_title {
            get {
                return ResourceManager.GetString("download_view_sort_filetime_end_desc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_sort_filetime_start_asc_title.
        /// </summary>
        internal static string download_view_sort_filetime_start_asc_title {
            get {
                return ResourceManager.GetString("download_view_sort_filetime_start_asc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_view_sort_filetime_start_desc_title.
        /// </summary>
        internal static string download_view_sort_filetime_start_desc_title {
            get {
                return ResourceManager.GetString("download_view_sort_filetime_start_desc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit_title.
        /// </summary>
        internal static string exit_title {
            get {
                return ResourceManager.GetString("exit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to framework_title.
        /// </summary>
        internal static string framework_title {
            get {
                return ResourceManager.GetString("framework_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issue_report_summary.
        /// </summary>
        internal static string issue_report_summary {
            get {
                return ResourceManager.GetString("issue_report_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license_title.
        /// </summary>
        internal static string license_title {
            get {
                return ResourceManager.GetString("license_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off_title.
        /// </summary>
        internal static string off_title {
            get {
                return ResourceManager.GetString("off_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on_title.
        /// </summary>
        internal static string on_title {
            get {
                return ResourceManager.GetString("on_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open_source_summary.
        /// </summary>
        internal static string open_source_summary {
            get {
                return ResourceManager.GetString("open_source_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open_title.
        /// </summary>
        internal static string open_title {
            get {
                return ResourceManager.GetString("open_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_about_summary.
        /// </summary>
        internal static string page_about_summary {
            get {
                return ResourceManager.GetString("page_about_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_about_title.
        /// </summary>
        internal static string page_about_title {
            get {
                return ResourceManager.GetString("page_about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_concurrent_summary.
        /// </summary>
        internal static string page_config_concurrent_summary {
            get {
                return ResourceManager.GetString("page_config_concurrent_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_concurrent_title.
        /// </summary>
        internal static string page_config_concurrent_title {
            get {
                return ResourceManager.GetString("page_config_concurrent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_concurrent_unit.
        /// </summary>
        internal static string page_config_concurrent_unit {
            get {
                return ResourceManager.GetString("page_config_concurrent_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_folder_browse.
        /// </summary>
        internal static string page_config_folder_browse {
            get {
                return ResourceManager.GetString("page_config_folder_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_folder_placeholder.
        /// </summary>
        internal static string page_config_folder_placeholder {
            get {
                return ResourceManager.GetString("page_config_folder_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_folder_summary.
        /// </summary>
        internal static string page_config_folder_summary {
            get {
                return ResourceManager.GetString("page_config_folder_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_folder_title.
        /// </summary>
        internal static string page_config_folder_title {
            get {
                return ResourceManager.GetString("page_config_folder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_header_summary.
        /// </summary>
        internal static string page_config_header_summary {
            get {
                return ResourceManager.GetString("page_config_header_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_header_title.
        /// </summary>
        internal static string page_config_header_title {
            get {
                return ResourceManager.GetString("page_config_header_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_merge_mode_balanced_description.
        /// </summary>
        internal static string page_config_merge_mode_balanced_description {
            get {
                return ResourceManager.GetString("page_config_merge_mode_balanced_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_merge_mode_balanced_title.
        /// </summary>
        internal static string page_config_merge_mode_balanced_title {
            get {
                return ResourceManager.GetString("page_config_merge_mode_balanced_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_merge_mode_data_integrity_description.
        /// </summary>
        internal static string page_config_merge_mode_data_integrity_description {
            get {
                return ResourceManager.GetString("page_config_merge_mode_data_integrity_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_merge_mode_data_integrity_title.
        /// </summary>
        internal static string page_config_merge_mode_data_integrity_title {
            get {
                return ResourceManager.GetString("page_config_merge_mode_data_integrity_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_merge_mode_high_performance_description.
        /// </summary>
        internal static string page_config_merge_mode_high_performance_description {
            get {
                return ResourceManager.GetString("page_config_merge_mode_high_performance_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_merge_mode_high_performance_title.
        /// </summary>
        internal static string page_config_merge_mode_high_performance_title {
            get {
                return ResourceManager.GetString("page_config_merge_mode_high_performance_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_merge_mode_summary.
        /// </summary>
        internal static string page_config_merge_mode_summary {
            get {
                return ResourceManager.GetString("page_config_merge_mode_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_merge_mode_title.
        /// </summary>
        internal static string page_config_merge_mode_title {
            get {
                return ResourceManager.GetString("page_config_merge_mode_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_open_runner.
        /// </summary>
        internal static string page_config_open_runner {
            get {
                return ResourceManager.GetString("page_config_open_runner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_progress_window_close_completed_summary.
        /// </summary>
        internal static string page_config_progress_window_close_completed_summary {
            get {
                return ResourceManager.GetString("page_config_progress_window_close_completed_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_progress_window_close_completed_title.
        /// </summary>
        internal static string page_config_progress_window_close_completed_title {
            get {
                return ResourceManager.GetString("page_config_progress_window_close_completed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_progress_window_close_open_file_summary.
        /// </summary>
        internal static string page_config_progress_window_close_open_file_summary {
            get {
                return ResourceManager.GetString("page_config_progress_window_close_open_file_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_progress_window_close_open_file_title.
        /// </summary>
        internal static string page_config_progress_window_close_open_file_title {
            get {
                return ResourceManager.GetString("page_config_progress_window_close_open_file_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_progress_window_close_open_folder_summary.
        /// </summary>
        internal static string page_config_progress_window_close_open_folder_summary {
            get {
                return ResourceManager.GetString("page_config_progress_window_close_open_folder_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_progress_window_close_open_folder_title.
        /// </summary>
        internal static string page_config_progress_window_close_open_folder_title {
            get {
                return ResourceManager.GetString("page_config_progress_window_close_open_folder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_progress_window_summary.
        /// </summary>
        internal static string page_config_progress_window_summary {
            get {
                return ResourceManager.GetString("page_config_progress_window_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_progress_window_title.
        /// </summary>
        internal static string page_config_progress_window_title {
            get {
                return ResourceManager.GetString("page_config_progress_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_save.
        /// </summary>
        internal static string page_config_save {
            get {
                return ResourceManager.GetString("page_config_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_save_error.
        /// </summary>
        internal static string page_config_save_error {
            get {
                return ResourceManager.GetString("page_config_save_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_save_success.
        /// </summary>
        internal static string page_config_save_success {
            get {
                return ResourceManager.GetString("page_config_save_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_summary.
        /// </summary>
        internal static string page_config_summary {
            get {
                return ResourceManager.GetString("page_config_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_svc_active_title.
        /// </summary>
        internal static string page_config_svc_active_title {
            get {
                return ResourceManager.GetString("page_config_svc_active_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_svc_inactive_title.
        /// </summary>
        internal static string page_config_svc_inactive_title {
            get {
                return ResourceManager.GetString("page_config_svc_inactive_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_temp_folder_default.
        /// </summary>
        internal static string page_config_temp_folder_default {
            get {
                return ResourceManager.GetString("page_config_temp_folder_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_temp_folder_placeholder.
        /// </summary>
        internal static string page_config_temp_folder_placeholder {
            get {
                return ResourceManager.GetString("page_config_temp_folder_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_temp_folder_summary.
        /// </summary>
        internal static string page_config_temp_folder_summary {
            get {
                return ResourceManager.GetString("page_config_temp_folder_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_temp_folder_title.
        /// </summary>
        internal static string page_config_temp_folder_title {
            get {
                return ResourceManager.GetString("page_config_temp_folder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_threads_summary.
        /// </summary>
        internal static string page_config_threads_summary {
            get {
                return ResourceManager.GetString("page_config_threads_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_threads_title.
        /// </summary>
        internal static string page_config_threads_title {
            get {
                return ResourceManager.GetString("page_config_threads_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_threads_unit.
        /// </summary>
        internal static string page_config_threads_unit {
            get {
                return ResourceManager.GetString("page_config_threads_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_config_title.
        /// </summary>
        internal static string page_config_title {
            get {
                return ResourceManager.GetString("page_config_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_action_delete_all_title.
        /// </summary>
        internal static string page_downloads_action_delete_all_title {
            get {
                return ResourceManager.GetString("page_downloads_action_delete_all_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_action_delete_completed_title.
        /// </summary>
        internal static string page_downloads_action_delete_completed_title {
            get {
                return ResourceManager.GetString("page_downloads_action_delete_completed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_action_pause_all_title.
        /// </summary>
        internal static string page_downloads_action_pause_all_title {
            get {
                return ResourceManager.GetString("page_downloads_action_pause_all_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_action_resume_all_title.
        /// </summary>
        internal static string page_downloads_action_resume_all_title {
            get {
                return ResourceManager.GetString("page_downloads_action_resume_all_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_action_retry_all_title.
        /// </summary>
        internal static string page_downloads_action_retry_all_title {
            get {
                return ResourceManager.GetString("page_downloads_action_retry_all_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_action_title.
        /// </summary>
        internal static string page_downloads_action_title {
            get {
                return ResourceManager.GetString("page_downloads_action_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_add_title.
        /// </summary>
        internal static string page_downloads_add_title {
            get {
                return ResourceManager.GetString("page_downloads_add_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_cancel.
        /// </summary>
        internal static string page_downloads_cancel {
            get {
                return ResourceManager.GetString("page_downloads_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_dialog_delete_all_summary.
        /// </summary>
        internal static string page_downloads_dialog_delete_all_summary {
            get {
                return ResourceManager.GetString("page_downloads_dialog_delete_all_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_dialog_delete_allcpl_summary.
        /// </summary>
        internal static string page_downloads_dialog_delete_allcpl_summary {
            get {
                return ResourceManager.GetString("page_downloads_dialog_delete_allcpl_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_dialog_pause_all_summary.
        /// </summary>
        internal static string page_downloads_dialog_pause_all_summary {
            get {
                return ResourceManager.GetString("page_downloads_dialog_pause_all_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_dialog_retry_all_summary.
        /// </summary>
        internal static string page_downloads_dialog_retry_all_summary {
            get {
                return ResourceManager.GetString("page_downloads_dialog_retry_all_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_empty_hint.
        /// </summary>
        internal static string page_downloads_empty_hint {
            get {
                return ResourceManager.GetString("page_downloads_empty_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_empty_title.
        /// </summary>
        internal static string page_downloads_empty_title {
            get {
                return ResourceManager.GetString("page_downloads_empty_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_open_folder.
        /// </summary>
        internal static string page_downloads_open_folder {
            get {
                return ResourceManager.GetString("page_downloads_open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_pause.
        /// </summary>
        internal static string page_downloads_pause {
            get {
                return ResourceManager.GetString("page_downloads_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_refresh_title.
        /// </summary>
        internal static string page_downloads_refresh_title {
            get {
                return ResourceManager.GetString("page_downloads_refresh_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_resume.
        /// </summary>
        internal static string page_downloads_resume {
            get {
                return ResourceManager.GetString("page_downloads_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_retry.
        /// </summary>
        internal static string page_downloads_retry {
            get {
                return ResourceManager.GetString("page_downloads_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_summary.
        /// </summary>
        internal static string page_downloads_summary {
            get {
                return ResourceManager.GetString("page_downloads_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_downloads_title.
        /// </summary>
        internal static string page_downloads_title {
            get {
                return ResourceManager.GetString("page_downloads_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_home_summary.
        /// </summary>
        internal static string page_home_summary {
            get {
                return ResourceManager.GetString("page_home_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_home_title.
        /// </summary>
        internal static string page_home_title {
            get {
                return ResourceManager.GetString("page_home_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_app_theme_summary.
        /// </summary>
        internal static string page_settings_app_theme_summary {
            get {
                return ResourceManager.GetString("page_settings_app_theme_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_app_theme_title.
        /// </summary>
        internal static string page_settings_app_theme_title {
            get {
                return ResourceManager.GetString("page_settings_app_theme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_auto_hide_nav_summary.
        /// </summary>
        internal static string page_settings_auto_hide_nav_summary {
            get {
                return ResourceManager.GetString("page_settings_auto_hide_nav_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_auto_hide_nav_title.
        /// </summary>
        internal static string page_settings_auto_hide_nav_title {
            get {
                return ResourceManager.GetString("page_settings_auto_hide_nav_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_corner_radius_summary.
        /// </summary>
        internal static string page_settings_corner_radius_summary {
            get {
                return ResourceManager.GetString("page_settings_corner_radius_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_corner_radius_title.
        /// </summary>
        internal static string page_settings_corner_radius_title {
            get {
                return ResourceManager.GetString("page_settings_corner_radius_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_display_material_summary.
        /// </summary>
        internal static string page_settings_display_material_summary {
            get {
                return ResourceManager.GetString("page_settings_display_material_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_display_material_title.
        /// </summary>
        internal static string page_settings_display_material_title {
            get {
                return ResourceManager.GetString("page_settings_display_material_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_languageset_display_summary.
        /// </summary>
        internal static string page_settings_languageset_display_summary {
            get {
                return ResourceManager.GetString("page_settings_languageset_display_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_languageset_display_title.
        /// </summary>
        internal static string page_settings_languageset_display_title {
            get {
                return ResourceManager.GetString("page_settings_languageset_display_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_languageset_title.
        /// </summary>
        internal static string page_settings_languageset_title {
            get {
                return ResourceManager.GetString("page_settings_languageset_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_personalization_title.
        /// </summary>
        internal static string page_settings_personalization_title {
            get {
                return ResourceManager.GetString("page_settings_personalization_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_rat_summary.
        /// </summary>
        internal static string page_settings_rat_summary {
            get {
                return ResourceManager.GetString("page_settings_rat_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_rat_title.
        /// </summary>
        internal static string page_settings_rat_title {
            get {
                return ResourceManager.GetString("page_settings_rat_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_summary.
        /// </summary>
        internal static string page_settings_summary {
            get {
                return ResourceManager.GetString("page_settings_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_title.
        /// </summary>
        internal static string page_settings_title {
            get {
                return ResourceManager.GetString("page_settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_available.
        /// </summary>
        internal static string page_settings_update_available {
            get {
                return ResourceManager.GetString("page_settings_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_cancel_btn.
        /// </summary>
        internal static string page_settings_update_cancel_btn {
            get {
                return ResourceManager.GetString("page_settings_update_cancel_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_check_btn.
        /// </summary>
        internal static string page_settings_update_check_btn {
            get {
                return ResourceManager.GetString("page_settings_update_check_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_checking.
        /// </summary>
        internal static string page_settings_update_checking {
            get {
                return ResourceManager.GetString("page_settings_update_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_current_version_title.
        /// </summary>
        internal static string page_settings_update_current_version_title {
            get {
                return ResourceManager.GetString("page_settings_update_current_version_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_download_btn.
        /// </summary>
        internal static string page_settings_update_download_btn {
            get {
                return ResourceManager.GetString("page_settings_update_download_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_downloading.
        /// </summary>
        internal static string page_settings_update_downloading {
            get {
                return ResourceManager.GetString("page_settings_update_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_downloading_progress.
        /// </summary>
        internal static string page_settings_update_downloading_progress {
            get {
                return ResourceManager.GetString("page_settings_update_downloading_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_error.
        /// </summary>
        internal static string page_settings_update_error {
            get {
                return ResourceManager.GetString("page_settings_update_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_idle.
        /// </summary>
        internal static string page_settings_update_idle {
            get {
                return ResourceManager.GetString("page_settings_update_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_install_btn.
        /// </summary>
        internal static string page_settings_update_install_btn {
            get {
                return ResourceManager.GetString("page_settings_update_install_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_new_version_title.
        /// </summary>
        internal static string page_settings_update_new_version_title {
            get {
                return ResourceManager.GetString("page_settings_update_new_version_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_ready.
        /// </summary>
        internal static string page_settings_update_ready {
            get {
                return ResourceManager.GetString("page_settings_update_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_title.
        /// </summary>
        internal static string page_settings_update_title {
            get {
                return ResourceManager.GetString("page_settings_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_update_uptodate.
        /// </summary>
        internal static string page_settings_update_uptodate {
            get {
                return ResourceManager.GetString("page_settings_update_uptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_vab_summary.
        /// </summary>
        internal static string page_settings_vab_summary {
            get {
                return ResourceManager.GetString("page_settings_vab_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_vab_title.
        /// </summary>
        internal static string page_settings_vab_title {
            get {
                return ResourceManager.GetString("page_settings_vab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report_issue_title.
        /// </summary>
        internal static string report_issue_title {
            get {
                return ResourceManager.GetString("report_issue_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save_title.
        /// </summary>
        internal static string save_title {
            get {
                return ResourceManager.GetString("save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_onlang_changed_summary.
        /// </summary>
        internal static string sys_need_restart_app_summary {
            get {
                return ResourceManager.GetString("sys_need_restart_app_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sys_noti_complete_summary.
        /// </summary>
        internal static string sys_noti_complete_summary {
            get {
                return ResourceManager.GetString("sys_noti_complete_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sys_notification_title.
        /// </summary>
        internal static string sys_notification_title {
            get {
                return ResourceManager.GetString("sys_notification_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task_num_title.
        /// </summary>
        internal static string task_num_title {
            get {
                return ResourceManager.GetString("task_num_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui_lib_title.
        /// </summary>
        internal static string ui_lib_title {
            get {
                return ResourceManager.GetString("ui_lib_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update_available_summary.
        /// </summary>
        internal static string update_available_summary {
            get {
                return ResourceManager.GetString("update_available_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version_title.
        /// </summary>
        internal static string version_title {
            get {
                return ResourceManager.GetString("version_title", resourceCulture);
            }
        }
    }
}
