<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <!-- Publish config -->
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
    
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <FileVersion>1.0.3.0</FileVersion>

    <RepositoryUrl>https://github.com/maihcx/PDownloader.git</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<AssemblyName>PDownloader Tray</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDownloader.CFS\PDownloader.CFS.csproj" />
    <ProjectReference Include="..\PDownloader.CoreClient\PDownloader.CoreClient.csproj" />
    <ProjectReference Include="..\PDownloader.Contracts\PDownloader.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Wpf.Ui">
      <HintPath>..\WPF-UI.LIB\Wpf.Ui.dll</HintPath>
    </Reference>
    <Reference Include="Wpf.Ui.Abstractions">
      <HintPath>..\WPF-UI.LIB\Wpf.Ui.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Wpf.Ui.DependencyInjection">
      <HintPath>..\WPF-UI.LIB\Wpf.Ui.DependencyInjection.dll</HintPath>
    </Reference>
    <Reference Include="Wpf.Ui.Tray">
      <HintPath>..\WPF-UI.LIB\Wpf.Ui.Tray.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app-100.png" />
    <Resource Include="Assets\app-256.png" />
    <Resource Include="Assets\app.ico">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Locales\String.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>String.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\MainWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Locales\String.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>String.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
