//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDownloader.Runner.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDownloader.Runner.Resources.Locales.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_title.
        /// </summary>
        internal static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel_title.
        /// </summary>
        internal static string cancel_title {
            get {
                return ResourceManager.GetString("cancel_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_completed_description.
        /// </summary>
        internal static string download_compact_status_completed_description {
            get {
                return ResourceManager.GetString("download_compact_status_completed_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_completed_title.
        /// </summary>
        internal static string download_compact_status_completed_title {
            get {
                return ResourceManager.GetString("download_compact_status_completed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_connecting_description.
        /// </summary>
        internal static string download_compact_status_connecting_description {
            get {
                return ResourceManager.GetString("download_compact_status_connecting_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_error_description.
        /// </summary>
        internal static string download_compact_status_error_description {
            get {
                return ResourceManager.GetString("download_compact_status_error_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_merging_description.
        /// </summary>
        internal static string download_compact_status_merging_description {
            get {
                return ResourceManager.GetString("download_compact_status_merging_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_no_threads_description.
        /// </summary>
        internal static string download_compact_status_no_threads_description {
            get {
                return ResourceManager.GetString("download_compact_status_no_threads_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_paused_download_description.
        /// </summary>
        internal static string download_compact_status_paused_download_description {
            get {
                return ResourceManager.GetString("download_compact_status_paused_download_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_paused_merge_description.
        /// </summary>
        internal static string download_compact_status_paused_merge_description {
            get {
                return ResourceManager.GetString("download_compact_status_paused_merge_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_paused_merge_title.
        /// </summary>
        internal static string download_compact_status_paused_merge_title {
            get {
                return ResourceManager.GetString("download_compact_status_paused_merge_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_queued_description.
        /// </summary>
        internal static string download_compact_status_queued_description {
            get {
                return ResourceManager.GetString("download_compact_status_queued_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_single_thread_description.
        /// </summary>
        internal static string download_compact_status_single_thread_description {
            get {
                return ResourceManager.GetString("download_compact_status_single_thread_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_single_thread_title.
        /// </summary>
        internal static string download_compact_status_single_thread_title {
            get {
                return ResourceManager.GetString("download_compact_status_single_thread_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_compact_status_unsupported_title.
        /// </summary>
        internal static string download_compact_status_unsupported_title {
            get {
                return ResourceManager.GetString("download_compact_status_unsupported_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_start_title.
        /// </summary>
        internal static string download_start_title {
            get {
                return ResourceManager.GetString("download_start_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_cancelled_title.
        /// </summary>
        internal static string download_status_cancelled_title {
            get {
                return ResourceManager.GetString("download_status_cancelled_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_completed_title.
        /// </summary>
        internal static string download_status_completed_title {
            get {
                return ResourceManager.GetString("download_status_completed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_connecting_title.
        /// </summary>
        internal static string download_status_connecting_title {
            get {
                return ResourceManager.GetString("download_status_connecting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_downloading_title.
        /// </summary>
        internal static string download_status_downloading_title {
            get {
                return ResourceManager.GetString("download_status_downloading_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_error_title.
        /// </summary>
        internal static string download_status_error_title {
            get {
                return ResourceManager.GetString("download_status_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_merging_title.
        /// </summary>
        internal static string download_status_merging_title {
            get {
                return ResourceManager.GetString("download_status_merging_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_paused_title.
        /// </summary>
        internal static string download_status_paused_title {
            get {
                return ResourceManager.GetString("download_status_paused_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_queued_title.
        /// </summary>
        internal static string download_status_queued_title {
            get {
                return ResourceManager.GetString("download_status_queued_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_status_retry_title.
        /// </summary>
        internal static string download_status_retry_title {
            get {
                return ResourceManager.GetString("download_status_retry_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_fragment_detail.
        /// </summary>
        internal static string download_thread_fragment_detail {
            get {
                return ResourceManager.GetString("download_thread_fragment_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_item_title.
        /// </summary>
        internal static string download_thread_item_title {
            get {
                return ResourceManager.GetString("download_thread_item_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_stage_audio.
        /// </summary>
        internal static string download_thread_stage_audio {
            get {
                return ResourceManager.GetString("download_thread_stage_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_stage_file.
        /// </summary>
        internal static string download_thread_stage_file {
            get {
                return ResourceManager.GetString("download_thread_stage_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_stage_hls.
        /// </summary>
        internal static string download_thread_stage_hls {
            get {
                return ResourceManager.GetString("download_thread_stage_hls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_stage_video.
        /// </summary>
        internal static string download_thread_stage_video {
            get {
                return ResourceManager.GetString("download_thread_stage_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_state_completed.
        /// </summary>
        internal static string download_thread_state_completed {
            get {
                return ResourceManager.GetString("download_thread_state_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_state_downloading.
        /// </summary>
        internal static string download_thread_state_downloading {
            get {
                return ResourceManager.GetString("download_thread_state_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_state_failed.
        /// </summary>
        internal static string download_thread_state_failed {
            get {
                return ResourceManager.GetString("download_thread_state_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_state_retrying.
        /// </summary>
        internal static string download_thread_state_retrying {
            get {
                return ResourceManager.GetString("download_thread_state_retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_state_waiting.
        /// </summary>
        internal static string download_thread_state_waiting {
            get {
                return ResourceManager.GetString("download_thread_state_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_visualization_title.
        /// </summary>
        internal static string download_thread_visualization_title {
            get {
                return ResourceManager.GetString("download_thread_visualization_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_visualization_unsupported_generic.
        /// </summary>
        internal static string download_thread_visualization_unsupported_generic {
            get {
                return ResourceManager.GetString("download_thread_visualization_unsupported_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download_thread_visualization_unsupported_ytdlp.
        /// </summary>
        internal static string download_thread_visualization_unsupported_ytdlp {
            get {
                return ResourceManager.GetString("download_thread_visualization_unsupported_ytdlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to err_download_folder_not_exists_title.
        /// </summary>
        internal static string err_download_folder_not_exists_title {
            get {
                return ResourceManager.GetString("err_download_folder_not_exists_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to err_download_pdcore_notvalid_title.
        /// </summary>
        internal static string err_download_pdcore_notvalid_title {
            get {
                return ResourceManager.GetString("err_download_pdcore_notvalid_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to err_download_uri_unavailable_title.
        /// </summary>
        internal static string err_download_uri_unavailable_title {
            get {
                return ResourceManager.GetString("err_download_uri_unavailable_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file_name_title.
        /// </summary>
        internal static string file_name_title {
            get {
                return ResourceManager.GetString("file_name_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileNameLabel.
        /// </summary>
        internal static string FileNameLabel {
            get {
                return ResourceManager.GetString("FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDownload.
        /// </summary>
        internal static string NewDownload {
            get {
                return ResourceManager.GetString("NewDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open_file_title.
        /// </summary>
        internal static string open_file_title {
            get {
                return ResourceManager.GetString("open_file_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open_folder_title.
        /// </summary>
        internal static string open_folder_title {
            get {
                return ResourceManager.GetString("open_folder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string pause_title {
            get {
                return ResourceManager.GetString("pause_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string resume_title {
            get {
                return ResourceManager.GetString("resume_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResumeAll.
        /// </summary>
        internal static string ResumeAll {
            get {
                return ResourceManager.GetString("ResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry_title.
        /// </summary>
        internal static string retry_title {
            get {
                return ResourceManager.GetString("retry_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save_to_title.
        /// </summary>
        internal static string save_to_title {
            get {
                return ResourceManager.GetString("save_to_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select_folder_title.
        /// </summary>
        internal static string select_folder_title {
            get {
                return ResourceManager.GetString("select_folder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending_command_title.
        /// </summary>
        internal static string sending_command_title {
            get {
                return ResourceManager.GetString("sending_command_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status_completed_title.
        /// </summary>
        internal static string status_completed_title {
            get {
                return ResourceManager.GetString("status_completed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stt_download_conneting_title.
        /// </summary>
        internal static string stt_download_conneting_title {
            get {
                return ResourceManager.GetString("stt_download_conneting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to threads_title.
        /// </summary>
        internal static string threads_title {
            get {
                return ResourceManager.GetString("threads_title", resourceCulture);
            }
        }
    }
}
