//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDownloader.TorrentSel.Resources.Locales;

[global::System.CodeDom.Compiler.GeneratedCode(
    "System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Runtime.CompilerServices.CompilerGenerated]
internal class String
{
    private static global::System.Resources.ResourceManager? _resourceManager;
    private static global::System.Globalization.CultureInfo? _resourceCulture;

    internal String()
    {
    }

    [global::System.ComponentModel.EditorBrowsable(
        global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager =>
        _resourceManager ??= new global::System.Resources.ResourceManager(
            "PDownloader.TorrentSel.Resources.Locales.String", typeof(String).Assembly);

    [global::System.ComponentModel.EditorBrowsable(
        global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo? Culture
    {
        get => _resourceCulture;
        set => _resourceCulture = value;
    }
}
